### ISSUE TITLE
Unable to view project

### ISSUE THREAD

**Issue by sethherr** [appsforartists/ambidex-example--bike-index#2]
It installs and  starts correctly, but then fails when I access http://tardis.local/

What's going wrong? (node via homebrew, OSX Mavericks)

```
module.js:340
    throw err;
          ^
Error: Cannot find module 'mach'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/Users/.../ambidex-example--bike-index/application/server.js:2:15)
    at Module._compile (module.js:456:26)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/.../ambidex-example--bike-index/node_modules/node-jsx/index.js:26:12)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
```

printout from npm-debug.log:

```
0 info it worked if it ends with ok
1 verbose cli [ 'node', '/usr/local/bin/npm', 'start', 'tardis' ]
2 info using npm@2.1.18
3 info using node@v0.10.35
4 verbose node symlink /usr/local/bin/node
5 verbose run-script [ 'prestart', 'start', 'poststart' ]
6 info prestart ambidex-example--bike-index@0.0.0
7 info start ambidex-example--bike-index@0.0.0
8 verbose unsafe-perm in lifecycle true
9 info ambidex-example--bike-index@0.0.0 Failed to exec start script
10 verbose stack Error: ambidex-example--bike-index@0.0.0 start: `node --harmony ./init.js tardis`
10 verbose stack Exit status 8
10 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:212:16)
10 verbose stack     at EventEmitter.emit (events.js:98:17)
10 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:14:12)
10 verbose stack     at ChildProcess.emit (events.js:98:17)
10 verbose stack     at maybeClose (child_process.js:766:16)
10 verbose stack     at Process.ChildProcess._handle.onexit (child_process.js:833:5)
11 verbose pkgid ambidex-example--bike-index@0.0.0
12 verbose cwd /Users/.../ambidex-example--bike-index
13 error Darwin 13.4.0
14 error argv "node" "/usr/local/bin/npm" "start" "tardis"
15 error node v0.10.35
16 error npm  v2.1.18
17 error code ELIFECYCLE
18 error ambidex-example--bike-index@0.0.0 start: `node --harmony ./init.js tardis`
18 error Exit status 8
19 error Failed at the ambidex-example--bike-index@0.0.0 start script 'node --harmony ./init.js tardis'.
19 error This is most likely a problem with the ambidex-example--bike-index package,
19 error not with npm itself.
```

**Comment by appsforartists** [comment]
Did you run `npm install` first?  It looks like [mach](https://github.com/mjackson/mach) is missing.

**Comment by sethherr** [comment]
I did npm install, it just didn't take. After your advice, did

```
npm unlink mach
npm install mach@1.1
```

And everything is working. Relatively unexperienced with node, thanks for your assistance!
